/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.panel.PanelLeft;
import view.panel.Panel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;

import model.Graph;
import view.panel.PanelMenu;

/**
 *
 * @author anderson
 */
public class FrameNewGraph extends javax.swing.JFrame {

    /**
     * Creates new form FrameNewGraph
     */
    public FrameNewGraph() {
        initComponents();
        componentHandling();
        setVisible(true);
    }
    
    private boolean checkOriented, checkWeighted;

    public void componentHandling(){
        ButtonHandler handler = new ButtonHandler();
        CheckBoxHandler check = new CheckBoxHandler();
        
        done.addActionListener(handler);
        oriented.addItemListener(check);
        weighted.addItemListener(check);
    }
    
    private class ButtonHandler implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent event){
            Frame.getUnit().fileNew();
            Graph.getUnit().setDirection(checkOriented);
            Graph.getUnit().setWeighted(checkWeighted);
            
            PanelLeft.getUnit().disableButtons();
            PanelMenu.getUnit().disableAlgorithms();
            
            Panel.getUnit().repaint();
            dispose();
        }// actionPerformed
    }// ButtonHandler
    
    private class CheckBoxHandler implements ItemListener{
        Graph graph = Graph.getUnit();
        
        @Override
        public void itemStateChanged(ItemEvent event){
            if(oriented.isSelected()){
                checkOriented = true;
            } else {
                checkOriented = false;
            }// if-else
            
            if(weighted.isSelected()){
                checkWeighted = true;
            } else {
                checkWeighted = false;
            }// if-else
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        oriented = new javax.swing.JCheckBox();
        weighted = new javax.swing.JCheckBox();
        done = new javax.swing.JButton();

        setTitle("New Graph");
        setLocation(new java.awt.Point(600, 300));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Choose your graph options ");

        oriented.setText("Oriented");

        weighted.setText("Weighted");

        done.setText("Done");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(oriented)
                    .addComponent(weighted)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(done))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oriented)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weighted)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(done)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox oriented;
    private javax.swing.JCheckBox weighted;
    // End of variables declaration//GEN-END:variables
}
