/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.*;
import model_control.Graph;

/**
 *
 * @author anderson
 */
public class PanelLeft extends javax.swing.JPanel {

    private static PanelLeft unit;
    public static PanelLeft getUnit(){
        if(unit == null)
            unit = new PanelLeft();
        return unit;
    }
    
    /**
     * Creates new form PanelLeft
     */
    private PanelLeft() {
        initComponents();
        disableButtons(!Graph.getUnit().isWeighted());
        buttonHandling();
    }
    
    boolean buttonDisabled = !Graph.getUnit().isWeighted();
    
    public void disableButtons(boolean b){
        bfs.setEnabled(b);
        dfs.setEnabled(b);
        prim.setEnabled(!b);
        editEdge.setEnabled(!b);
        dijkstra.setEnabled(!b);
        edkarp.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addVertex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        removeVertex = new javax.swing.JButton();
        editVertex = new javax.swing.JButton();
        addEdge = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        removeEdge = new javax.swing.JButton();
        editEdge = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bfs = new javax.swing.JButton();
        dfs = new javax.swing.JButton();
        prim = new javax.swing.JButton();
        dijkstra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        speed = new javax.swing.JButton();
        random = new javax.swing.JButton();
        digraph = new javax.swing.JButton();
        weight = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        edkarp = new javax.swing.JButton();

        setBackground(new java.awt.Color(61, 135, 84));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setDoubleBuffered(false);
        setFocusable(false);

        addVertex.setBackground(new java.awt.Color(61, 135, 84));
        addVertex.setForeground(new java.awt.Color(61, 135, 84));
        addVertex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addVertex.setToolTipText("add vertex");
        addVertex.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addVertex.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("vertex");
        jLabel1.setFocusable(false);

        removeVertex.setBackground(new java.awt.Color(61, 135, 84));
        removeVertex.setForeground(new java.awt.Color(61, 135, 84));
        removeVertex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        removeVertex.setToolTipText("Remove Vertex");
        removeVertex.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeVertex.setFocusable(false);

        editVertex.setBackground(new java.awt.Color(61, 135, 84));
        editVertex.setForeground(new java.awt.Color(61, 135, 84));
        editVertex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editVertex.setToolTipText("Vertex Info");
        editVertex.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editVertex.setFocusable(false);

        addEdge.setBackground(new java.awt.Color(61, 135, 84));
        addEdge.setForeground(new java.awt.Color(61, 135, 84));
        addEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addEdge.setToolTipText("Add Edge / Click");
        addEdge.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addEdge.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("edge");
        jLabel2.setFocusable(false);

        removeEdge.setBackground(new java.awt.Color(61, 135, 84));
        removeEdge.setForeground(new java.awt.Color(61, 135, 84));
        removeEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        removeEdge.setToolTipText("Remove Edge / Click");
        removeEdge.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        removeEdge.setFocusable(false);

        editEdge.setBackground(new java.awt.Color(61, 135, 84));
        editEdge.setForeground(new java.awt.Color(61, 135, 84));
        editEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editEdge.setToolTipText("Edit Edge");
        editEdge.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editEdge.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("algorithms");
        jLabel3.setFocusable(false);

        bfs.setBackground(new java.awt.Color(61, 135, 84));
        bfs.setForeground(new java.awt.Color(61, 135, 84));
        bfs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alg1.png"))); // NOI18N
        bfs.setToolTipText("play BFS");
        bfs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        dfs.setBackground(new java.awt.Color(61, 135, 84));
        dfs.setForeground(new java.awt.Color(61, 135, 84));
        dfs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alg2.png"))); // NOI18N
        dfs.setToolTipText("play DFS");
        dfs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        prim.setBackground(new java.awt.Color(61, 135, 84));
        prim.setForeground(new java.awt.Color(61, 135, 84));
        prim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alg3.png"))); // NOI18N
        prim.setToolTipText("play Prim");
        prim.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        dijkstra.setBackground(new java.awt.Color(61, 135, 84));
        dijkstra.setForeground(new java.awt.Color(61, 135, 84));
        dijkstra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/alg4.png"))); // NOI18N
        dijkstra.setToolTipText("play Dijkstra");
        dijkstra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("configuration");
        jLabel4.setFocusable(false);

        speed.setBackground(new java.awt.Color(61, 135, 84));
        speed.setForeground(new java.awt.Color(61, 135, 84));
        speed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/speed.png"))); // NOI18N
        speed.setToolTipText("algorithm speed");
        speed.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        speed.setFocusable(false);

        random.setBackground(new java.awt.Color(61, 135, 84));
        random.setForeground(new java.awt.Color(61, 135, 84));
        random.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/random.png"))); // NOI18N
        random.setToolTipText("generate random graph");
        random.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        random.setFocusable(false);

        digraph.setBackground(new java.awt.Color(61, 135, 84));
        digraph.setForeground(new java.awt.Color(61, 135, 84));
        digraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/digraph.png"))); // NOI18N
        digraph.setToolTipText("digraph / simple graph");
        digraph.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        digraph.setFocusable(false);

        weight.setBackground(new java.awt.Color(61, 135, 84));
        weight.setForeground(new java.awt.Color(61, 135, 84));
        weight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/weighted.png"))); // NOI18N
        weight.setToolTipText("weighted / nonweighted graph");
        weight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        weight.setFocusable(false);

        jSeparator1.setBackground(new java.awt.Color(46, 101, 63));
        jSeparator1.setForeground(new java.awt.Color(46, 101, 63));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        edkarp.setBackground(new java.awt.Color(61, 135, 84));
        edkarp.setForeground(new java.awt.Color(61, 135, 84));
        edkarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/flow.png"))); // NOI18N
        edkarp.setToolTipText("play Edmonds-Karp");
        edkarp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(random, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(digraph, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bfs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dfs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(edkarp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editVertex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bfs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dfs, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(random, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(digraph, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(edkarp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void buttonHandling(){
        ButtonHandler handler = new ButtonHandler();
        addVertex.addActionListener(handler);
        removeVertex.addActionListener(handler);
        editVertex.addActionListener(handler);
        bfs.addActionListener(handler);
        dfs.addActionListener(handler);
        prim.addActionListener(handler);
        dijkstra.addActionListener(handler);
        random.addActionListener(handler);
        digraph.addActionListener(handler);
        speed.addActionListener(handler);
        weight.addActionListener(handler);
        addEdge.addActionListener(handler);
        removeEdge.addActionListener(handler);
        editEdge.addActionListener(handler);
        edkarp.addActionListener(handler);
    }
    
    private class ButtonHandler implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ex){
            Frame f = Frame.getUnit();
            if(ex.getSource() == addVertex){
                f.addVertex();
            }
            if(ex.getSource() == addEdge){
                new FrameEdge(1);
            }
            if(ex.getSource() == removeEdge){
                new FrameEdge(2);
            }            
            if(ex.getSource() == editEdge){
                new FrameEdgeEdit();
            }
            if(ex.getSource() == bfs){
                f.bfs();
            }
            if(ex.getSource() == dfs){
                f.dfs();
            }
            if(ex.getSource() == prim){
                f.prim();
            }
            if(ex.getSource() == dijkstra){
                f.dijkstra();
            }
            if(ex.getSource() == random){
                f.configRandomFrame();
            }
            if(ex.getSource() == digraph){
                f.digraph();
            }
            if(ex.getSource() == weight){
                buttonDisabled = !buttonDisabled;
                disableButtons(buttonDisabled);
                f.weighted();
            }
            if(ex.getSource() == speed){
                f.configSpeed();
            }
            if(ex.getSource() == removeVertex){
                f.removeVertex();
            }
            if(ex.getSource() == editVertex){
                new FrameVertex();
            }
            if(ex.getSource() == edkarp){
                f.disableButtons();
                new FrameEdge(3);
            }
            Panel.getUnit().repaint();
        }

    }// ButtonHandler

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEdge;
    private javax.swing.JButton addVertex;
    private javax.swing.JButton bfs;
    private javax.swing.JButton dfs;
    private javax.swing.JButton digraph;
    private javax.swing.JButton dijkstra;
    private javax.swing.JButton editEdge;
    private javax.swing.JButton editVertex;
    private javax.swing.JButton edkarp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton prim;
    private javax.swing.JButton random;
    private javax.swing.JButton removeEdge;
    private javax.swing.JButton removeVertex;
    private javax.swing.JButton speed;
    private javax.swing.JButton weight;
    // End of variables declaration//GEN-END:variables


}
